main: codes.biscuit.chunkbuster.ChunkBuster
version: ${version}
api-version: 1.13
name: ChunkBuster
author: Biscut
depend: [LGCore]
softdepend: [MassiveCore, Factions, WorldGuard, CoreProtect, Towny, WorldEdit]

commit-hash: ${git.commit.id.describe-short}
git-repo: LemonGamingLtd/ChunkBuster

commands:
  chunkbuster:
    description: Give a player (a) chunkbuster(s).
    aliases: [cb]
permissions:
  chunkbuster.give:
    description: Access to the /cb give command.
    default: op
  chunkbuster.reload:
    description: Access to the /cb reload command.
    default: op
  chunkbuster.water:
    description: Access to the /cb water command.
    default: op
  chunkbuster.admin:
    description: Access to the /cb command.
    default: op
    children:
      chunkbuster.give: true
      chunkbuster.reload: true
      chunkbuster.water: true
  chunkbuster.use:
    description: Be able to place chunkbusters.
    default: true